version: "3"

services:
  ### SETUP SERVER CONTAINER
  server:
    # Build the server from
    build:
      context: ./src
      dockerfile: Dockerfile
    # Ports expose
    expose:
      - 3000
    # Port mapping
    ports:
      - 3000:3000
    # Volumes to mount
    volumes:
      - ./src/:/app/src
      - /app/src/node_modules
      - /app/src/.next
    # Run command
    command: yarn dev
    # Restart
    restart: always
